# Harmony Jekyll theme general configurations

# Base URL
baseurl:

# Site live URL
url: http://zhanghaowx.github.io

# Localhost
# url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  # Webpage title
  name: "&lt;Escape /&gt;"
  # Little description about your site
  description: Stay hungry. Stay foolish.
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and
  # in your feed.xml site description.
  meta_description: > #
   Hao Zhang's personal blog.

  basetheme: theme-base-default # pre defined themes are darken, blue-water, redish.
  author: # Author details
    name: Hao Zhang
    email: zhanghaowx@gmail.com
    url: http://zhanghaowx.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-39152444-2
  google_font_delay_load: false

  # Profile links, leave blank to ignore
  social:
    github: zhanghaowx
    twitter:
    facebook: haozhangcs
    gplus: +haozhang88
    dribble:
    pinterest:

  # Toggle disclaimer in footer
  show_disclaimer: false
  # Toggle page background by particles.js
  show_particles_background: true

  # Choose page load indicator's theme by pace.js
  # Look at files assets/css/plugins/pace/pace-*.scss for possible values
  # Leave empty if don't want pace.js
  pace_theme:

  layout:
    sidebar: true

  post:
    timeline: true

# Conversion / Build settings
markdown: kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache

# Sass conversion configs
sass:
  sass_dir: assets/css/partials
  style: :compressed
